// DiscordSlashCommandBot
// Copyright (C) 2022 Mark E. Kraus
// 
// This program is free software: you can redistribute it and/or modify it under the terms of the GNU Affero General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
// 
// This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Affero General Public License for more details.
// 
// You should have received a copy of the GNU Affero General Public License along with this program. If not, see <https://www.gnu.org/licenses/>.

using Discord;
using Discord.WebSocket;

namespace DiscordSlashCommandBot.Interfaces
{
    /// <summary>
    /// Interface for discord slash commands.
    /// Used by <see cref="DiscordSlashCommandBot.Services.BotService"/> to register and process slash commands.
    /// </summary>
    public interface IBotSlashCommand
    {
         /// <summary>
         /// Get's the <see cref="SlashCommandBuilder"/> used to build the slash command by <see cref="DiscordSlashCommandBot.Services.BotService"/>.
         /// </summary>
         /// <returns><see cref="SlashCommandBuilder"/></returns>
         SlashCommandBuilder GetSlashCommandBuilder();
         
         /// <summary>
         /// Callback method used to process slash commands by <see cref="DiscordSlashCommandBot.Services.BotService"/>.
         /// </summary>
         /// <param name="command">The <see cref="SocketSlashCommand"/> generated by the discord client.</param>
         /// <returns><see cref="Task"/></returns>
         Task SlashCommandHandler(SocketSlashCommand command);
    }
}